version: '3.8'

services:
  backend:
    stdin_open: true
    tty: true
    container_name: django-dev
    build: ./testassigment
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./testassigment/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./testassigment/.env
    depends_on:
      - db

  db:
    container_name: db-dev
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=django
      - POSTGRES_USER=django
      - POSTGRES_DB=django

  frontend:
    container_name: frontend-dev
    build: ./chrome-ux-report-app
    command: npm start
    volumes:
      - ./chrome-ux-report-app/:/app/
    ports:
      - 3000:3000

volumes:
  postgres_data:
