# Generated by Django 4.2.6 on 2024-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux', '0002_remove_record_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='birthdate',
            field=models.CharField(max_length=20),
        ),
    ]
