# Generated by Django 4.2.6 on 2024-03-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crux', '0003_alter_record_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='score',
            field=models.CharField(max_length=100),
        ),
    ]
